# netlify.toml

[build]
  command = "npm install"
  functions = "functions"
  publish = "public"
  [build.environment]
    NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  included_files = [
      "node_modules/airtable/**",
      "node_modules/memory-cache/**",
      "node_modules/async-retry/**",
      "node_modules/@sentry/aws-serverless/**"
  ]

[context.production.environment]
  AIRTABLE_TABLE_RESERVAS = "tblJSKGb4IBeyUwyo"
  AIRTABLE_TABLE_EXPERIENCES = "tblJ604IExFMU3KvW"
  AIRTABLE_TABLE_FOOD = "tblz3fbgTFnqfCGi9"
  # SET AIRTABLE_API_KEY and SENTRY_DSN in Netlify UI

[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - Removed npmcdn.com
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' https://cdn.jsdelivr.net https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css; img-src 'self' data:; font-src 'self' https://cdn.jsdelivr.net; connect-src 'self' *.sentry.io;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200