# netlify.toml

[build]
  command = "npm install"
  functions = "functions"
  publish = "public"
  # ADD THIS SECTION (or add NODE_VERSION to existing environment section)
  [build.environment]
    NODE_VERSION = "18" # Specifies Node.js version 18 LTS

# Environment variables specific to the production context
[context.production.environment]
  AIRTABLE_TABLE_RESERVAS = "tblJSKGb4IBeyUwyo"
  AIRTABLE_TABLE_EXPERIENCES = "tblaBc1QhlksnV5Qb"
  AIRTABLE_TABLE_FOOD = "tblz3fbgTFnqfCGi9"
  # Your Sentry DSN etc...
  # SENTRY_DSN = "YOUR_SENTRY_DSN_HERE" # Set via Netlify UI

# --- Custom Headers ---
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' https://cdn.jsdelivr.net; img-src 'self' https://images.fillout.com data:; font-src 'self' https://cdn.jsdelivr.net; connect-src 'self' *.sentry.io;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"


# Redirects/Rewrites
[[redirects]]
  # Map requests from the user-friendly /api/* path...
  from = "/api/*"
  # ...to the actual Netlify function location.
  # The ':splat' captures everything after /api/ and passes it on.
  # Status 200 makes it an internal rewrite (proxy) instead of a browser redirect.
  to = "/.netlify/functions/:splat"
  status = 200
  # Optional: Force it if other rules might interfere, unlikely needed here
  # force = true